version: "3.7"
services:
  discoveryservice:
    image: rishikesh12/discoveryservice
    build:
      context: DiscoveryServer
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - users-network
  zuul:
    image: rishikesh12/zuulapigateway
    build:
      context: ZuulApiGateway
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryservice:8761/eureka
    ports:
      - "8090:8090"
    restart: always
    depends_on:
      - discoveryservice
    networks:
      - users-network
  authentication-ms:
    image: rishikesh12/authentication-ms
    build:
      context: Authentication-Microservice
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryservice:8761/eureka
    depends_on:
      - discoveryservice
    networks:
      - users-network
  customer-ms:
    image: rishikesh12/customer-ms
    build:
      context: Customer-Microservice
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryservice:8761/eureka
      AUTHENTICATION_URI: http://authentication-ms:8081/authentication-ms
      ACCOUNT_URI: http://account-ms:8083/account-ms
    depends_on:
      - discoveryservice
    networks:
      - users-network
  account-ms:
    image: rishikesh12/account-ms
    build:
      context: Account-Microservice
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryservice:8761/eureka
      AUTHENTICATION_URI: http://authentication-ms:8081/authentication-ms
      CUSTOMER_URI: http://customer-ms:8082/customer-ms
      TRANSACTION_URI: http://transaction-ms:8084/transaction-ms
    depends_on:
      - discoveryservice
    networks:
      - users-network
  transaction-ms:
    image: rishikesh12/transaction-ms
    build:
      context: Transaction-Microservice
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryservice:8761/eureka
      ACCOUNT_URI: http://account-ms:8083/account-ms
      RULES_URI: http://rules-ms:8085/rules-ms
    depends_on:
      - discoveryservice
    networks:
      - users-network
  rules-ms:
    image: rishikesh12/rules-ms
    build:
      context: Rules-Microservice
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    restart: always
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryservice:8761/eureka
      AUTHENTICATION_URI: http://authentication-ms:8081/authentication-ms
      ACCOUNT_URI: http://account-ms:8083/account-ms
    depends_on:
      - discoveryservice
    networks:
      - users-network

# Networks to be created to facilitate communication between containers
networks:
  users-network:
